# Generated by Django 2.1.2 on 2018-10-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
